### ISSUE TITLE
Broken dependence for 24.10

### ISSUE THREAD

**Issue by lancelot96** [cpiber/hyprland-ppa#3]
libaquamarine4 depends libdisplay-info1, but 24.10 only have libdisplay-info2

**Comment by cpiber** [comment]
I'm using 24.10 myself, so it should work. But you may need to enable proposed, I'll check in the evening

**Comment by cpiber** [comment]
Ah, no, I use 24.04 and that's correct. I don't currently build for oracular, does apt allow you to install the noble packages anyway? I'll investigate how much work it is to build for oracular as well

**Comment by lancelot96** [comment]
I can download and install libdisplay-info1 from Internet, and working as expected

**Comment by cpiber** [comment]
Took a while to publish, but the Hyprland packages should now be properly available for oracular, not just for noble (you added the noble repo before). `xdg-desktop-portal-hyprland` also had some dependency problems. Waybar and the plugins are still publishing, so they'll require some time.

Please be aware that I don't have a 24.10 system setup. I checked in a chroot that all dependencies are available and link correctly, but no real running test.
