### ISSUE TITLE
Add support for Debian 13

### ISSUE THREAD

**Issue by carlo711** [cpiber/hyprland-ppa#4]
Currently `apt install hyprland` on Debian 13 fails, caused by missing dependencies.

I added and pinned the ppa-repo, tried noble as well as oracular via: `deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/hyprland-ppa-keyring.gpg] https://ppa.launchpadcontent.net/cppiber/hyprland/ubuntu oracular main`

pinning config:
```
Package: *
Pin: origin "ppa.launchpadcontent.net"
Pin-Priority: 999
```
This should update all available and needed packages for hyprland from the ppa rather than the official repos.

```zsh
carlo@debian:~/dev$ sudo apt install hyprland
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

Unsatisfied dependencies:
 hyprland : Depends: libhyprcursor1 (>= 0.1.11) but it is not going to be installed
            Depends: libhyprgraphics0 (>= 0.1.1) but it is not going to be installed
            Depends: libre2-10 (>= 20150701+dfsg) but it is not installable
            Recommends: xdg-desktop-portal-hyprland but it is not going to be installed or
                        xdg-desktop-portal-wlr but it is not going to be installed
            Recommends: xdg-desktop-portal-gtk but it is not going to be installed
            Recommends: sway-notification-center but it is not going to be installed or
                        dunst but it is not going to be installed
            Recommends: pipewire but it is not going to be installed
            Recommends: wireplumber but it is not going to be installed
            Recommends: hyprland-qtutils but it is not going to be installed
Error: Unable to correct problems, you have held broken packages.
```

I then tried to build for the sources but wasn't successfully either. The upstream moved to re2 and I suspect, that this package is not available in the offical repos. `apt search libre2` confirmed this:
```bash
libdjvulibre21/testing 3.5.28-2+b2 amd64
  Runtime support for the DjVu image format

libpcre2-dev/testing 10.44-5 amd64
  New Perl Compatible Regular Expression Library - development files

libre2-11/testing,now 20240501-3+b1 amd64 [installed]
  efficient, principled regular expression library

libre2-dev/testing 20240501-3+b1 amd64
  efficient, principled regular expression library, development kit

libre2j-java/testing 1.7+dfsg-1 all
  RE2/J: linear time regular expression matching in Java
```
Currently, only libre2-11 exists but not libre2-10.

**System Details:**

    Distribution: Debian 13 (Trixie)
    Kernel Version: 6.11.10-amd64

**Comment by cpiber** [comment]
Unfortunately, launchpad does not allow me to publish for debian.

Starting with Debian 13, gcc-13 and gcc-14 are available, so building is relatively straightforward. The scripts for building the packages are now documented in the Readme, use `sbuild`, `debuild`, or any other tool you are comfortable with to build the actual package.
I've also now pushed a small update to the scripts. If you run `./scripts/open-build.sh <package> trixie`, it will automatically remove patches not necessary on debian. For other versions of debian, patches need to be tested first. You can then build using whichever tool you prefer (but make sure to build with trixie packages).

I've built the packages in the following order:
- hyprutils
- hyprlang
- aquamarine
- hyprcursor
- hyprgraphics
- udis86
- hyprland-protocols
- hyprwayland-scanner
- hyprland-data
- hyprland-stable (or alternatively hyprland)

Strongly recommended:
- hyprland-qtutils
- xdg-desktop-portal-hyprland

Other suggested packages (didn't try to build):
- hypridle
- hyprlock
- hyprpaper
- hyprpicker
- hyprpolkitagent
- hyprsunset
- hyprsysteminfo
- iio-hyprland
- waybar / waybar-unstable

If you want plugins, these packages are available:
- hyprland-plugin-deps is a virtual package which depends on build dependencies
- hyprland-plugins official hyprland plugins https://github.com/hyprwm/hyprland-plugins/
- hyprscroller https://github.com/dawsers/hyprscroller
Note that the latter two explicitly depend on unstable. You probably have to adjust the `debian/control` file to the version you have built (after open-build.sh in the build folder).

**Comment by carlo711** [comment]
Thank you for the instructions!

If have rerun the build process for trixie(testing) and can confirm, that the following packages can be build:

- hyprutils
- hyprlang
- aquamarine
- hyprcursor
- hyprgraphics
- udis86
- hyprland-protocols
- hyprwayland-scanner
- hyprland-data
- hyprland-stable
- xdg-desktop-portal-hyprland (near recent version in trixie-repo)

Following utils can be build:

- hypridle
- hyprlock
- hyprpaper
- hyprpicker
- hyprpolkitagent
- hyprsunset
- hyprsysteminfo
- iio-hyprland
- hyprland-qtutils

Not able to build:

- waybar (most recent version is in trixie-repo)

Not tried hyprland-plugins nor hyprscroller, maybe will give it a try in the future.

**Note for building**: Used the build order as the packages above. At first I was unable to build the qutils, but tried again at the end were all other utils has been build, it then magically worked


**Note for installing**: I had to manually install libjxl10(from sid repo) and xwayland, in order to make hyprland run.
