### ISSUE TITLE
Update on 24.10 with libre2-10

### ISSUE THREAD

**Issue by cgiuliani** [cpiber/hyprland-ppa#5]
Hello,  
For some time now, it has not been possible to update the **hyprland** package on Ubuntu 24.10 because the dependency **libre2-10** is not satisfied.  

```
Unsatisfied dependencies:  
hyprland : Depends: libre2-10 (>= 20150701+dfsg) but it is not installable
```

**PS:** Thank you for maintaining this PPA!

**Comment by cpiber** [comment]
Interesting, I did not realize, it seems at some point Ubuntu introduced a different package name (compared to 20.04), will rebuild shortly

**Comment by cpiber** [comment]
Stable is published and should be updatable now, unstable still working
